# Generated by Django 3.2.6 on 2021-08-29 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_question_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['time_poll']},
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
